# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sealab-api:
    image: sealab-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    extra_hosts:
      - "see.labs.telkomuniversity.ac.id:103.233.100.16"
